/**
 * Lucide 图标集接入（Vuetify 自定义 SVG 图标集）
 *
 * 2026-09-18：全项目图标由 Material Design Icons（@mdi/font 字体）迁移到
 * Lucide（lucide-vue-next 组件），用户认为 mdi 字形"太粗糙/太丑"。
 *
 * 工作机制：
 * - `defaultSet: 'lucide'` + `sets.lucide.component`：所有显式 `icon="mdi-x"` /
 *   prepend-icon / `:icon` / `icon` 对象字段的字符串照常传入（组件零改动），
 *   渲染组件剥掉 `mdi-` 前缀后经 `mdiMap` 落到对应的 Lucide 组件。
 * - `aliases`：Vuetify 内部别名（$close/$prev/$checkboxOn…）直接挂 Lucide 组件
 *   （VIcon 对非字符串 icon 走 VComponentIcon，逐组件渲染，同样生效）。
 * - 尺寸/颜色：VIcon 外层 `.v-icon` 的 font-size 与 color 决定表现，全局 CSS
 *   强制 `.v-icon svg { width:1em; height:1em }` 使 SVG 随父级缩放、
 *   stroke=currentColor 继承主题色。
 *
 * 维护：新增 mdi 图标名必须在 `mdiMap` 登记，否则回退 CircleHelp（语义兜底）。
 */
import { h, defineComponent, type Component } from 'vue'
import type { IconAliases, IconSet } from 'vuetify'
import {
  AlignLeft,
  ArrowDown,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightFromLine,
  ArrowUp,
  ArrowUpDown,
  ArrowUpNarrowWide,
  Ban,
  Bell,
  Bookmark,
  Bot,
  CalendarDays,
  CaseLower,
  CaseUpper,
  ChartArea,
  ChartBar,
  ChartLine,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  CircleUserRound,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardType,
  Clock,
  Code,
  Columns3,
  Container,
  Copy,
  CopyPlus,
  CopyX,
  Cpu,
  Database,
  DatabaseBackup,
  Dices,
  Download,
  Ellipsis,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileInput,
  FileOutput,
  FileText,
  FoldVertical,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderInput,
  FolderTree,
  FunctionSquare,
  GitCompare,
  HeartPulse,
  Highlighter,
  History,
  Info,
  Key,
  KeyRound,
  Keyboard,
  Languages,
  LayoutDashboard,
  Link2,
  ListTree,
  LoaderCircle,
  Lock,
  LockOpen,
  MemoryStick,
  Menu,
  Minus,
  MonitorOff,
  Network,
  Palette,
  PanelLeft,
  PanelsTopLeft,
  Pencil,
  Pin,
  PinOff,
  Pipette,
  Play,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  Route,
  Rows3,
  Save,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  SkipForward,
  SlidersHorizontal,
  SlidersVertical,
  Sparkles,
  Square,
  SquareCheckBig,
  SquareDashed,
  SquareMinus,
  SquarePen,
  SquarePlus,
  SquareTerminal,
  SquareX,
  Star,
  StarHalf,
  StarOff,
  Table2,
  TableProperties,
  Terminal,
  TextCursorInput,
  Trash2,
  TriangleAlert,
  Type,
  Undo2,
  Unplug,
  Upload,
  Usb,
  UserRoundMinus,
  UserRoundPlus,
  Wrench,
  X,
  Zap,
} from 'lucide-vue-next'

/**
 * mdi 图标名（去 `mdi-` 前缀小写）→ Lucide 组件。
 * 完整清单由 `grep -rhoE "mdi-[a-zA-Z0-9-]+" src --include=*.vue --include=*.ts | sort -u`
 * 导出后逐条对照 lucide.dev 语义映射；无直接等价取近义词。
 */
const mdiMap: Record<string, Component> = {
  'account-key-outline': KeyRound,
  'account-outline': CircleUserRound,
  'account-plus': UserRoundPlus,
  'account-remove': UserRoundMinus,
  alert: TriangleAlert,
  'alert-circle': CircleAlert,
  'alert-circle-outline': CircleAlert,
  'alert-outline': TriangleAlert,
  'arrow-collapse-horizontal': ArrowLeftRight,
  'arrow-collapse-vertical': FoldVertical,
  'arrow-down': ArrowDown,
  'arrow-expand-vertical': ArrowUpDown,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  'auto-fix': Sparkles,
  'bell-outline': Bell,
  'bookmark-outline': Bookmark,
  broom: Eraser,
  'calendar-blank-outline': CalendarDays,
  'chart-areaspline': ChartArea,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-tree': ListTree,
  check: Check,
  'check-all': CheckCheck,
  'check-circle': CircleCheck,
  'check-circle-outline': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-outline': Circle,
  'clipboard-check-outline': ClipboardCheck,
  'clipboard-text-outline': ClipboardType,
  'clock-outline': Clock,
  close: X,
  'close-box-multiple-outline': SquareX,
  'close-circle': CircleX,
  'close-circle-multiple-outline': CopyX,
  'code-tags': Code,
  'cog-outline': Settings,
  compare: GitCompare,
  'compare-horizontal': GitCompare,
  console: Terminal,
  'console-line': SquareTerminal,
  'console-network': SquareTerminal,
  'content-copy': Copy,
  'content-duplicate': CopyPlus,
  'content-paste': Clipboard,
  'content-save': Save,
  'content-save-outline': Save,
  'cpu-64-bit': Cpu,
  database: Database,
  'database-arrow-right-outline': ArrowRightFromLine,
  'database-export': Download,
  'database-import': Upload,
  'database-outline': Database,
  'database-plus': Plus,
  'database-plus-outline': Plus,
  'database-refresh-outline': DatabaseBackup,
  'database-remove': Trash2,
  delete: Trash2,
  'delete-outline': Trash2,
  'dice-multiple-outline': Dices,
  docker: Container,
  'dots-horizontal': Ellipsis,
  eraser: Eraser,
  eye: Eye,
  'eye-off': EyeOff,
  'eye-outline': Eye,
  'file-export-outline': FileOutput,
  'file-import-outline': FileInput,
  'file-outline': FileText,
  'file-tree': FolderTree,
  'file-tree-outline': FolderTree,
  'flash-outline': Zap,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-open-outline': FolderOpen,
  'folder-outline': Folder,
  'folder-plus-outline': FolderPlus,
  'folder-swap-outline': FolderInput,
  'form-textbox': TextCursorInput,
  'format-align-left': AlignLeft,
  'format-font': Type,
  'format-letter-case-lower': CaseLower,
  'format-letter-case-upper': CaseUpper,
  function: FunctionSquare,
  'function-variant': FunctionSquare,
  'heart-pulse': HeartPulse,
  'help-circle': CircleHelp,
  'help-circle-outline': CircleHelp,
  history: History,
  'information-outline': Info,
  key: KeyRound,
  'key-chain-variant': Link2,
  'key-variant': Key,
  'keyboard-outline': Keyboard,
  'keyboard-settings-outline': Keyboard,
  lan: Network,
  'lan-connect': Network,
  'lan-disconnect': Unplug,
  'lock-open-variant-outline': LockOpen,
  'lock-outline': Lock,
  magnify: Search,
  marker: Highlighter,
  memory: MemoryStick,
  'monitor-dashboard': LayoutDashboard,
  'monitor-off': MonitorOff,
  null: Ban,
  'open-in-new': ExternalLink,
  'palette': Palette,
  'palette-outline': Palette,
  pencil: Pencil,
  'pencil-box-outline': SquarePen,
  'pencil-outline': Pencil,
  pin: Pin,
  'pin-off': PinOff,
  play: Play,
  'play-circle-outline': CirclePlay,
  plus: Plus,
  'plus-box-outline': SquarePlus,
  'plus-circle-outline': CirclePlus,
  printer: Printer,
  'record-circle-outline': CircleDot,
  refresh: RefreshCw,
  'rename-box': SquarePen,
  restart: RotateCcw,
  'robot-outline': Bot,
  routes: Route,
  'script-text-outline': ScrollText,
  'select-all': SquareCheckBig,
  send: Send,
  'send-outline': Send,
  'serial-port': Usb,
  server: Server,
  'server-network': Server,
  'shield-lock-outline': ShieldCheck,
  sitemap: Network,
  'skip-over': SkipForward,
  sort: ArrowDownUp,
  'sort-ascending': ArrowUpNarrowWide,
  'sort-descending': ArrowDownWideNarrow,
  star: Star,
  'star-off': StarOff,
  'star-outline': Star,
  'star-plus-outline': Star,
  stop: Square,
  'swap-horizontal': ArrowLeftRight,
  'swap-vertical': ArrowUpDown,
  tab: SquareDashed,
  'tab-minus': SquareMinus,
  'tab-remove': SquareX,
  table: Table2,
  'table-arrow-right': Table2,
  'table-check': Table2,
  'table-cog': TableProperties,
  'table-column': Columns3,
  'table-edit': TableProperties,
  'table-plus': Plus,
  'table-remove': Trash2,
  'table-row': Rows3,
  'text-box-outline': FileText,
  translate: Languages,
  tune: SlidersHorizontal,
  'tune-vertical': SlidersVertical,
  undo: Undo2,
  'usb-port': Usb,
  'view-sidebar': PanelLeft,
  'window-restore': PanelsTopLeft,
  wrench: Wrench,
  x: X,
}

/**
 * Vuetify 内部别名（$xxx）→ Lucide 组件。
 * 值直接挂组件：VIcon 对非字符串 icon 走 VComponentIcon 渲染，绕过自建 set。
 * 键盘键帽（command/ctrl/space/shift/alt/enter/箭头/backspace）本项目未使用，省略。
 */
/**
 * 单选框选中态自定义图标：外圈圆环 + 中心实心圆点（12px 图标下中心点恰 6px）。
 * Lucide Dot 是纯小圆点（无外圈）、CircleDot 中心点 12px 下仅 ~2.5px 偏小，均不满足
 * （用户指定「橙色实心圆环+中心6px圆，未选12px空心圆」）。
 */
const RadioOnDot = defineComponent({
  name: 'FyRadioOnDot',
  setup() {
    return () =>
      h('svg', {
        xmlns: 'http://www.w3.org/2000/svg',
        width: '24',
        height: '24',
        viewBox: '0 0 24 24',
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': '2',
        'stroke-linecap': 'round',
        'stroke-linejoin': 'round',
      }, [
        h('circle', { cx: '12', cy: '12', r: '10' }),
        h('circle', { cx: '12', cy: '12', r: '6', fill: 'currentColor', stroke: 'none' }),
      ])
  },
})

export const aliases: Partial<IconAliases> = {
  collapse: ChevronUp,
  complete: Check,
  cancel: CircleX,
  close: X,
  delete: X,
  clear: X,
  success: CircleCheck,
  info: Info,
  warning: TriangleAlert,
  error: CircleAlert,
  prev: ChevronLeft,
  next: ChevronRight,
  checkboxOn: SquareCheckBig,
  checkboxOff: Square,
  checkboxIndeterminate: Minus,
  delimiter: Circle,
  sortAsc: ArrowUpNarrowWide,
  sortDesc: ArrowDownWideNarrow,
  expand: ChevronDown,
  menu: Menu,
  subgroup: ChevronDown,
  dropdown: ChevronDown,
  radioOn: RadioOnDot,
  radioOff: Circle,
  edit: Pencil,
  ratingEmpty: Star,
  ratingFull: Star,
  ratingHalf: StarHalf,
  loading: LoaderCircle,
  first: ChevronsLeft,
  last: ChevronsRight,
  unfold: ChevronsUpDown,
  file: File,
  plus: Plus,
  minus: Minus,
  calendar: CalendarDays,
  treeviewCollapse: ChevronDown,
  treeviewExpand: ChevronRight,
  eyeDropper: Pipette,
  upload: Upload,
  download: Download,
  color: Palette,
}

/**
 * IconSet 渲染组件：接收 VIcon 转来的 icon 字符串（显式用如 `mdi-magnify`，
 * 或 alias 解析后的名字），剥 `mdi-` 前缀后查 mdiMap。
 */
const LucideIcon = defineComponent({
  // inheritAttrs 默认 true：VIcon 传入的 class="v-icon …" 与 style(尺寸/颜色) 自动落到 <i> 根节点
  name: 'FyLucideIcon',
  props: {
    icon: { type: [String, Array, Object, Function], default: '' },
    // VIcon 传 tag 恒为 'i'（字符串），收窄类型避免 h() 对 Function 重载歧义
    tag: { type: String, default: 'i' },
  },
  setup(props) {
    return () => {
      const name =
        typeof props.icon === 'string' ? props.icon.replace(/^mdi-/, '').toLowerCase() : ''
      const Icon = mdiMap[name] ?? CircleHelp
      return h(props.tag, null, [h(Icon, { 'aria-hidden': 'true' })])
    }
  },
})

/** Lucide 图标集（挂载到 defaultSet: 'lucide'） */
export const lucideIconSet = { component: LucideIcon } as IconSet
