// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  会话/文件夹树（扁平：文件夹+会话混合节点，前端按 folderId/parentId 组树）
	 * 
	 *  契约签名为 `()`；`filter` 为可选扩展参数（Tauri 允许省略 Option 参数），
	 *  前端搜索过滤可下沉到 Rust 侧执行。
	 */
	sessionList: (filter: string | null) => __TAURI_INVOKE<SessionNode[]>("session_list", { filter }),
	/**  保存会话（新会话生成 id） */
	sessionSave: (config: SessionConfig) => __TAURI_INVOKE<SessionConfig>("session_save", { config }),
	/**  删除会话或文件夹（is_folder 区分，前端已二次确认） */
	sessionDelete: (id: string, isFolder: boolean) => __TAURI_INVOKE<null>("session_delete", { id, isFolder }),
	/**
	 *  测试连接：一次性"连接 + 认证 + 断开"的轻量测试，返回 `{ ok, message }`
	 * 
	 *  State 由 Tauri 注入（不属于前端 IPC 签名），仅用于 Jump 时读取被引用的跳板会话。
	 */
	sessionTest: (config: SessionConfig) => __TAURI_INVOKE<TestResult>("session_test", { config }),
	/**  保存文件夹（新文件夹生成 id） */
	folderSave: (folder: SessionFolder) => __TAURI_INVOKE<SessionFolder>("folder_save", { folder }),
	/**  导航树批量重排（拖拽归类/排序）：folders/sessions 父级与顺序一次事务更新 */
	sessionReorder: (items: NodeReorderItem[]) => __TAURI_INVOKE<null>("session_reorder", { items }),
	/**
	 *  建立 SSH 连接并打开 PTY/shell；终端输出流走 Channel（契约：`ssh_connect(id, onOutput)`）。
	 *  conn_id：多标签同会话独立连接的路由键（Xshell 行为：每个标签一条独立连接）。
	 */
	sshConnect: (id: string, connId: string | null, onOutput: Channel<number[]>) => __TAURI_INVOKE<null>("ssh_connect", { id, connId, onOutput }),
	/**  关闭并清理 session/PTY（契约红线：标签关闭时 Rust 侧同步清理） */
	sshDisconnect: (id: string) => __TAURI_INVOKE<null>("ssh_disconnect", { id }),
	/**  键盘输入写入（按会话 ID 路由） */
	sshWrite: (id: string, data: number[]) => __TAURI_INVOKE<null>("ssh_write", { id, data }),
	/**  终端尺寸变更（按会话 ID 路由 resize） */
	sshResize: (id: string, cols: number, rows: number) => __TAURI_INVOKE<null>("ssh_resize", { id, cols, rows }),
	/**
	 *  HostKey 首次确认：前端确认后取出 AppState::pending_hostkey 中的
	 *  oneshot::Sender 并 send(bool)，挂起中的连接验证随之继续或中止。
	 */
	sshHostkeyAccept: (id: string, accept: boolean) => __TAURI_INVOKE<null>("ssh_hostkey_accept", { id, accept }),
	/**
	 *  终端 rz/sz 文件传输的用户选择回传：收到 rzsz-start 事件后
	 *  前端弹对话框，用户选择接收（local_path 为保存目录）/ 发送（local_path
	 *  为本地文件）/ 取消后调用本命令，选择经响应通道传给传输任务。
	 */
	rzszRespond: (key: string, action: string, localPath: string) => __TAURI_INVOKE<null>("rzsz_respond", { key, action, localPath }),
	debugLog: (message: string) => __TAURI_INVOKE<void>("debug_log", { message }),
	/**  目录列表：`Vec<FileEntry>` */
	sftpList: (id: string, path: string) => __TAURI_INVOKE<FileEntry[]>("sftp_list", { id, path }),
	/**  创建目录 */
	sftpMkdir: (id: string, path: string) => __TAURI_INVOKE<null>("sftp_mkdir", { id, path }),
	/**  删除（前端二次确认；目录递归删除） */
	sftpDelete: (id: string, path: string, isDir: boolean) => __TAURI_INVOKE<null>("sftp_delete", { id, path, isDir }),
	/**  重命名 */
	sftpRename: (id: string, oldPath: string, newPath: string) => __TAURI_INVOKE<null>("sftp_rename", { id, oldPath, newPath }),
	/**  设置文件/目录权限（chmod）：`mode` 为八进制语义数值（如 0o644 = 420） */
	sftpChmod: (id: string, path: string, mode: number) => __TAURI_INVOKE<null>("sftp_chmod", { id, path, mode }),
	/**  读取远程文件内容为 UTF-8 文本（文本编辑用；≤2MB，非 UTF-8/二进制报错） */
	sftpReadText: (id: string, path: string) => __TAURI_INVOKE<string>("sftp_read_text", { id, path }),
	/**  写回远程文件内容（全量 TRUNCATE 覆盖，UTF-8）——文本编辑保存 */
	sftpWriteText: (id: string, path: string, content: string) => __TAURI_INVOKE<null>("sftp_write_text", { id, path, content }),
	/**  入队上传，进度走 Channel（返回含 id 的任务快照，前端可凭其取消） */
	sftpUpload: (id: string, localPath: string, remotePath: string, onProgress: Channel<TransferTask>) => __TAURI_INVOKE<TransferTask>("sftp_upload", { id, localPath, remotePath, onProgress }),
	/**  入队下载，进度走 Channel */
	sftpDownload: (id: string, remotePath: string, localPath: string, onProgress: Channel<TransferTask>) => __TAURI_INVOKE<TransferTask>("sftp_download", { id, remotePath, localPath, onProgress }),
	/**  传输队列快照：`Vec<TransferTask>` */
	transferList: () => __TAURI_INVOKE<TransferTask[]>("transfer_list"),
	/**  取消任务：写入取消集合，传输循环每批检查命中即中止 */
	transferCancel: (taskId: string) => __TAURI_INVOKE<null>("transfer_cancel", { taskId }),
	/**  清除已完成 / 失败 / 已取消记录（Queued / Running 保留） */
	transferClear: () => __TAURI_INVOKE<null>("transfer_clear"),
	/**  本地目录列表（供双栏左侧使用）；路径为 ".." 时返回上级目录列表 */
	localList: (path: string) => __TAURI_INVOKE<FileEntry[]>("local_list", { path }),
	/**
	 *  本地文件系统起点列表（供内置文件选择器作为初始视图）：
	 *  Windows 返回各盘符（name 形如 "C:"，前端拼 "C:/" 后调 local_list）；
	 *  其他平台返回根 "/"。name 均以 is_dir=true 标记，语义与 local_list 一致。
	 */
	localListRoots: () => __TAURI_INVOKE<FileEntry[]>("local_list_roots"),
	/**
	 *  自研调用 Windows 原生文件对话框（IFileOpenDialog，即资源管理器选择器）：
	 *  send=选单个文件 / recv=选目录；用户取消返回 None。
	 *  可选 title（对话框标题）与 filter_name/filter_exts（文件扩展名过滤，如 json）。
	 * 
	 *  不走任何第三方插件（替代 tauri-plugin-dialog）：
	 *  对话框经 run_on_main_thread 在主线程（有消息泵）模态展示，
	 *  父窗口为主窗口，保证置顶与输入焦点正确。
	 */
	localPickDialog: (mode: string, title: string | null, filterName: string | null, filterExts: string[] | null) => __TAURI_INVOKE<string | null>("local_pick_dialog", { mode, title, filterName, filterExts }),
	/**
	 *  自研调用 Windows 原生保存对话框（IFileSaveDialog，带覆盖确认）：
	 *  default_path 为默认文件名；用户取消返回 None。参数语义同 local_pick_dialog。
	 */
	localSaveDialog: (defaultPath: string, title: string | null, filterName: string | null, filterExts: string[] | null) => __TAURI_INVOKE<string | null>("local_save_dialog", { defaultPath, title, filterName, filterExts }),
	/**  本地新建文件夹（fe-sftp 双栏本地侧） */
	localMkdir: (path: string) => __TAURI_INVOKE<null>("local_mkdir", { path }),
	/**  本地重命名 */
	localRename: (oldPath: string, newPath: string) => __TAURI_INVOKE<null>("local_rename", { oldPath, newPath }),
	/**  本地删除：is_dir 为 true 时递归删除目录，否则删除文件 */
	localDelete: (path: string, isDir: boolean) => __TAURI_INVOKE<null>("local_delete", { path, isDir }),
	/**  SFTP 收藏路径列表（按收藏时间倒序） */
	sftpFavoriteList: () => __TAURI_INVOKE<SftpFavorite[]>("sftp_favorite_list"),
	/**  收藏路径：按 (side, path) 幂等，返回含 id 的收藏记录 */
	sftpFavoriteAdd: (side: string, path: string) => __TAURI_INVOKE<SftpFavorite>("sftp_favorite_add", { side, path }),
	/**  取消收藏：按侧 + 路径删除（未收藏时幂等） */
	sftpFavoriteRemove: (side: string, path: string) => __TAURI_INVOKE<null>("sftp_favorite_remove", { side, path }),
	/**
	 *  快捷命令/文件夹树（扁平：文件夹+命令混合节点，前端按 groupId/parentId 组树）
	 * 
	 *  契约签名为 `()`。
	 */
	qcList: () => __TAURI_INVOKE<QuickCommandNode[]>("qc_list"),
	/**  保存快捷命令（新命令生成 id） */
	qcSaveCommand: (cmd: QuickCommand) => __TAURI_INVOKE<QuickCommand>("qc_save_command", { cmd }),
	/**  保存快捷命令文件夹（新文件夹生成 id） */
	qcSaveFolder: (folder: QuickCommandFolder) => __TAURI_INVOKE<QuickCommandFolder>("qc_save_folder", { folder }),
	/**  删除快捷命令或文件夹（is_folder 区分，前端已二次确认） */
	qcDelete: (id: string, isFolder: boolean) => __TAURI_INVOKE<null>("qc_delete", { id, isFolder }),
	/**  隧道规则列表：`session_id` 非空时仅返回该会话的规则 */
	tunnelList: (sessionId: string | null) => __TAURI_INVOKE<TunnelRule[]>("tunnel_list", { sessionId }),
	/**  保存规则（新规则的 id 为空时由后端生成；upsert），返回含 id 的规则快照 */
	tunnelSave: (rule: TunnelRule) => __TAURI_INVOKE<TunnelRule>("tunnel_save", { rule }),
	/**  删除规则并停止（未启动的隧道忽略停止步骤） */
	tunnelDelete: (id: string) => __TAURI_INVOKE<null>("tunnel_delete", { id }),
	/**  启动监听 */
	tunnelStart: (id: string) => __TAURI_INVOKE<null>("tunnel_start", { id }),
	/**  停止监听 */
	tunnelStop: (id: string) => __TAURI_INVOKE<null>("tunnel_stop", { id }),
	/**  一键全启：遍历全部规则逐个启动（已在运行中的跳过），返回成功/失败计数 */
	tunnelStartAll: () => __TAURI_INVOKE<StartAllReport>("tunnel_start_all"),
	/**
	 *  会话克隆：读原配置 → 新 uuid → 名称加"副本"后缀 → save_session → 返回新配置
	 * 
	 *  克隆复制完整配置（含 folder_id / auth_type / profile_id 引用），不建立连接。
	 */
	sessionClone: (id: string) => __TAURI_INVOKE<SessionConfig>("session_clone", { id }),
	/**  输出落盘开关（某会话） */
	sessionLogToggle: (sessionId: string, enabled: boolean) => __TAURI_INVOKE<null>("session_log_toggle", { sessionId, enabled }),
	/**  某会话的日志日期列表（YYYY-MM-DD，升序） */
	sessionLogList: (sessionId: string) => __TAURI_INVOKE<string[]>("session_log_list", { sessionId }),
	/**  读取某会话某天的日志内容（date 格式必须为 YYYY-MM-DD） */
	sessionLogRead: (sessionId: string, date: string) => __TAURI_INVOKE<string>("session_log_read", { sessionId, date }),
	/**  列出全部认证配置文件 */
	authProfileList: () => __TAURI_INVOKE<AuthProfile[]>("auth_profile_list"),
	/**  保存认证配置文件（新配置文件生成 id；一处改全局生效） */
	authProfileSave: (profile: AuthProfile) => __TAURI_INVOKE<AuthProfile>("auth_profile_save", { profile }),
	/**  删除认证配置文件（引用它的会话不删除，profile_id 引用被置空） */
	authProfileDelete: (id: string) => __TAURI_INVOKE<null>("auth_profile_delete", { id }),
	/**  `mysql_connect` (config: MySqlConnection) -> String connection_id */
	mysqlConnect: (config: MySqlConnection) => __TAURI_INVOKE<string>("mysql_connect", { config }),
	/**  `mysql_disconnect` (conn_id: String) -> () */
	mysqlDisconnect: (connId: string) => __TAURI_INVOKE<null>("mysql_disconnect", { connId }),
	/**
	 *  `mysql_list_tables` (conn_id: String [, db: String]) -> Vec<MySqlTableInfo>
	 * 
	 *  db 可选：未传时列当前默认库的表（工作台/网格惯例）；传入时列指定库的表
	 *  （工具对话框「数据传输/数据同步」的源库下拉联动，`db` 限定不依赖连接当前库）。
	 */
	mysqlListTables: (connId: string, db: string | null) => __TAURI_INVOKE<MySqlTableInfo[]>("mysql_list_tables", { connId, db }),
	/**  `mysql_query` (conn_id: String, sql: String, page: u32, page_size: u32) -> MySqlQueryResult */
	mysqlQuery: (connId: string, sql: string, page: number, pageSize: number) => __TAURI_INVOKE<MySqlQueryResult>("mysql_query", { connId, sql, page, pageSize }),
	/**
	 *  `mysql_execute` (conn_id: String, sql: String [, confirmed: bool]) -> u64 受影响行数
	 * 
	 *  `confirmed` 为契约扩展的可选参数：前端首次调用不传，命中危险 SQL 时收到
	 *  错误提示并二次确认，确认后带 `confirmed: true` 重新调用。
	 */
	mysqlExecute: (connId: string, sql: string, confirmed: boolean | null) => __TAURI_INVOKE<number>("mysql_execute", { connId, sql, confirmed }),
	/**
	 *  `mysql_cli_exec` (conn_id: String, sql: String) -> MySqlQueryResult
	 * 
	 *  命令列界面专用：任意语句直接执行（不做 COUNT 包装与分页），
	 *  行语句返回全部列与行（最多 1000 行），非行语句 total 为受影响行数。
	 */
	mysqlCliExec: (connId: string, sql: string) => __TAURI_INVOKE<MySqlQueryResult>("mysql_cli_exec", { connId, sql }),
	/**  `mysql_begin` (conn_id: String) -> 开启事务 */
	mysqlBegin: (connId: string) => __TAURI_INVOKE<null>("mysql_begin", { connId }),
	/**  `mysql_commit` (conn_id: String) -> 提交事务 */
	mysqlCommit: (connId: string) => __TAURI_INVOKE<null>("mysql_commit", { connId }),
	/**  `mysql_rollback` (conn_id: String) -> 回滚事务 */
	mysqlRollback: (connId: string) => __TAURI_INVOKE<null>("mysql_rollback", { connId }),
	/**  `redis_connect` (config: RedisConnection) -> String connection_id */
	redisConnect: (config: RedisConnection) => __TAURI_INVOKE<string>("redis_connect", { config }),
	/**  `redis_disconnect` (conn_id: String) -> () */
	redisDisconnect: (connId: string) => __TAURI_INVOKE<null>("redis_disconnect", { connId }),
	/**  `redis_test` (config: RedisConnection) -> String 服务器版本摘要 */
	redisTest: (config: RedisConnection) => __TAURI_INVOKE<string>("redis_test", { config }),
	/**  `redis_info` (conn_id: String) -> Vec<(String, String)> 键值对 */
	redisInfo: (connId: string) => __TAURI_INVOKE<([string, string])[]>("redis_info", { connId }),
	/**  `redis_select_db` (conn_id: String, db: u8) -> 切换库 */
	redisSelectDb: (connId: string, db: number) => __TAURI_INVOKE<null>("redis_select_db", { connId, db }),
	/**  `redis_keys` (conn_id: String, pattern: String) -> Vec<String> */
	redisKeys: (connId: string, pattern: string) => __TAURI_INVOKE<string[]>("redis_keys", { connId, pattern }),
	/**  `redis_exec` (conn_id: String, args: Vec<String>) -> RedisExecResult */
	redisExec: (connId: string, args: string[]) => __TAURI_INVOKE<RedisExecResult>("redis_exec", { connId, args }),
	/**  `mysql_table_design_get` (conn_id: String, table: String) -> MySqlTableDesign */
	mysqlTableDesignGet: (connId: string, table: string) => __TAURI_INVOKE<MySqlTableDesign>("mysql_table_design_get", { connId, table }),
	/**
	 *  `mysql_table_design_save` (conn_id: String, change: MySqlDesignChange) -> String 生成的 DDL 文本
	 * 
	 *  先经 validate_change 基础校验，再逐条执行 DDL；返回的 DDL 文本供前端展示预览。
	 */
	mysqlTableDesignSave: (connId: string, change: MySqlDesignChange) => __TAURI_INVOKE<string>("mysql_table_design_save", { connId, change }),
	/**  `mysql_history_list` (limit: u32) -> Vec<MySqlQueryHistoryItem> */
	mysqlHistoryList: (limit: number) => __TAURI_INVOKE<MySqlQueryHistoryItem[]>("mysql_history_list", { limit }),
	/**  `mysql_history_search` (keyword: String, limit: u32) -> Vec<MySqlQueryHistoryItem> */
	mysqlHistorySearch: (keyword: string, limit: number) => __TAURI_INVOKE<MySqlQueryHistoryItem[]>("mysql_history_search", { keyword, limit }),
	/**  `mysql_history_clear` () -> 清空全部查询历史 */
	mysqlHistoryClear: () => __TAURI_INVOKE<null>("mysql_history_clear"),
	/**
	 *  `mysql_explain` (conn_id: String, sql: String [, analyze: bool]) -> MySqlExplainResult
	 * 
	 *  `analyze` 为可选参数（默认 false）：true 时使用 EXPLAIN ANALYZE（真实执行
	 *  语句，后端仅允许 SELECT 开头的语句，写语句返回错误提示）。
	 */
	mysqlExplain: (connId: string, sql: string, analyze: boolean | null) => __TAURI_INVOKE<MySqlExplainResult>("mysql_explain", { connId, sql, analyze }),
	/**  `mysql_saved_query_list` () -> Vec<MySqlSavedQueryItem> */
	mysqlSavedQueryList: () => __TAURI_INVOKE<MySqlSavedQueryItem[]>("mysql_saved_query_list"),
	/**
	 *  `mysql_saved_query_save` (name: String, conn_id: Option<String>, sql: String [, overwrite: bool]) -> bool（true = 覆盖了同名）
	 * 
	 *  新增或覆盖：同名且未带 `overwrite=true` 时返回带提示错误，前端覆盖确认后
	 *  重新调用（与 mysql_update_row 的 confirmed 流程一致）。
	 *  `conn_id` 可空：None 表示不绑定连接（全局可见）。
	 */
	mysqlSavedQuerySave: (name: string, connId: string | null, sql: string, overwrite: boolean | null) => __TAURI_INVOKE<boolean>("mysql_saved_query_save", { name, connId, sql, overwrite }),
	/**
	 *  `mysql_saved_query_rename` (id: i64, name: String) -> 重命名（按 id 定位）
	 * 
	 *  新名称与其它条目冲突（UNIQUE）时返回带提示错误。
	 */
	mysqlSavedQueryRename: (id: number, name: string) => __TAURI_INVOKE<null>("mysql_saved_query_rename", { id, name }),
	/**  `mysql_saved_query_delete` (id: i64) -> 删除（按 id 定位） */
	mysqlSavedQueryDelete: (id: number) => __TAURI_INVOKE<null>("mysql_saved_query_delete", { id }),
	/**  `mysql_edit_preview` (conn_id: String, update: MySqlRowUpdate) -> MySqlEditPreview */
	mysqlEditPreview: (connId: string, update: MySqlRowUpdate) => __TAURI_INVOKE<MySqlEditPreview>("mysql_edit_preview", { connId, update }),
	/**
	 *  `mysql_update_rows` (conn_id: String, batch: MySqlRowUpdateBatch [, confirmed: bool]) -> u64 总受影响行数
	 * 
	 *  批量条目全部按主键定位（生成的 UPDATE 恒含 WHERE，无全表风险），
	 *  `confirmed` 参数为管道一致性保留；批量默认以隐式事务包裹，失败整体回滚。
	 */
	mysqlUpdateRows: (connId: string, batch: MySqlRowUpdateBatch, confirmed: boolean | null) => __TAURI_INVOKE<number>("mysql_update_rows", { connId, batch, confirmed }),
	/**
	 *  `mysql_delete_row` (conn_id: String, table: String, pk_column: String, pk_value: Option<String> [, confirmed: bool]) -> u64 受影响行数
	 * 
	 *  按主键定位删除，SQL 恒含 WHERE（非无 WHERE 的危险 DELETE），
	 *  `confirmed` 参数为管道一致性保留。
	 */
	mysqlDeleteRow: (connId: string, table: string, pkColumn: string, pkValue: string | null, confirmed: boolean | null) => __TAURI_INVOKE<number>("mysql_delete_row", { connId, table, pkColumn, pkValue, confirmed }),
	/**
	 *  `mysql_insert_rows` (conn_id: String, table: String, columns: Vec<String>, rows: Vec<Vec<Option<String>>> [, confirmed: bool]) -> u64 插入行数
	 * 
	 *  原生插入命令：事务包裹（失败整体回滚）、逐行参数化 INSERT（值经 `?` 占位符
	 *  二进制协议传输，防注入）；columns 为空表示逐行插入全默认值行。
	 *  `confirmed` 参数与 mysql_update_rows / mysql_delete_row 一致（管道一致性保留）。
	 */
	mysqlInsertRows: (connId: string, table: string, columns: string[], rows: ((string | null)[])[], confirmed: boolean | null) => __TAURI_INVOKE<number>("mysql_insert_rows", { connId, table, columns, rows, confirmed }),
	/**  `mysql_export` (conn_id: String, options: MySqlExportOptions) -> MySqlIoResult */
	mysqlExport: (connId: string, options: MySqlExportOptions) => __TAURI_INVOKE<MySqlIoResult>("mysql_export", { connId, options }),
	/**
	 *  `mysql_import` (conn_id: String, options: MySqlImportOptions [, confirmed: bool]) -> MySqlIoResult
	 * 
	 *  `confirmed` 为契约扩展的可选参数：options.replace 为 true（REPLACE INTO 覆盖
	 *  已有主键）时，前端首次调用不传，收到错误提示并二次确认，确认后带
	 *  `confirmed: true` 重新调用。
	 */
	mysqlImport: (connId: string, options: MySqlImportOptions, confirmed: boolean | null) => __TAURI_INVOKE<MySqlIoResult>("mysql_import", { connId, options, confirmed }),
	/**
	 *  `mysql_data_transfer` (source_conn_id: String, options: MySqlTransferOptions)
	 *  -> Vec<MySqlTransferTableResult>（逐表行数与跳过标记）
	 */
	mysqlDataTransfer: (sourceConnId: string, options: MySqlTransferOptions) => __TAURI_INVOKE<MySqlTransferTableResult[]>("mysql_data_transfer", { sourceConnId, options }),
	/**  `mysql_data_generate` (conn_id: String, options: MySqlGenerateOptions) -> u64（插入行数） */
	mysqlDataGenerate: (connId: string, options: MySqlGenerateOptions) => __TAURI_INVOKE<number>("mysql_data_generate", { connId, options }),
	/**
	 *  `mysql_data_sync` (source_conn_id: String, options: MySqlDataSyncOptions [, execute: bool])
	 *  -> MySqlDataSyncOutcome（execute=false 仅比对返回差异，true 按选项应用）
	 */
	mysqlDataSync: (sourceConnId: string, options: MySqlDataSyncOptions, execute: boolean | null) => __TAURI_INVOKE<MySqlDataSyncOutcome>("mysql_data_sync", { sourceConnId, options, execute }),
	/**
	 *  `mysql_structure_sync` (source_conn_id: String, options: MySqlStructureSyncOptions [, execute: bool])
	 *  -> MySqlStructureSyncPlan（execute=false 仅比对返回计划，true 在目标端执行）
	 */
	mysqlStructureSync: (sourceConnId: string, options: MySqlStructureSyncOptions, execute: boolean | null) => __TAURI_INVOKE<MySqlStructureSyncPlan>("mysql_structure_sync", { sourceConnId, options, execute }),
	/**  `mysql_object_list` (conn_id: String, kind: String) -> Vec<MySqlObjectInfo> */
	mysqlObjectList: (connId: string, kind: string) => __TAURI_INVOKE<MySqlObjectInfo[]>("mysql_object_list", { connId, kind }),
	/**  `mysql_object_ddl` (conn_id: String, kind: String, name: String) -> MySqlObjectDdl */
	mysqlObjectDdl: (connId: string, kind: string, name: string) => __TAURI_INVOKE<MySqlObjectDdl>("mysql_object_ddl", { connId, kind, name }),
	/**
	 *  `mysql_object_save` (conn_id: String, kind: String, name: String, create_sql: String) -> ()
	 * 
	 *  create_sql 为前端编辑后的完整 CREATE 语句；校验失败（首词非 CREATE /
	 *  OR REPLACE、对象名含反引号）返回错误，保存语义为「替换旧对象」。
	 */
	mysqlObjectSave: (connId: string, kind: string, name: string, createSql: string) => __TAURI_INVOKE<null>("mysql_object_save", { connId, kind, name, createSql }),
	/**  `mysql_object_drop` (conn_id: String, kind: String, name: String) -> () */
	mysqlObjectDrop: (connId: string, kind: string, name: string) => __TAURI_INVOKE<null>("mysql_object_drop", { connId, kind, name }),
	/**  `mysql_db_list` (conn_id: String) -> MySqlDatabaseList（host + current_db + databases） */
	mysqlDbList: (connId: string) => __TAURI_INVOKE<MySqlDatabaseList>("mysql_db_list", { connId }),
	/**
	 *  `mysql_db_create` (conn_id: String, name: String [, charset: String [, collation: String]]) -> ()
	 * 
	 *  新建数据库（CREATE DATABASE），charset/collation 可选（库默认字符集/排序规则，
	 *  右键菜单「新建数据库...」对话框选择，未传时使用服务器默认值）。
	 */
	mysqlDbCreate: (connId: string, name: string, charset: string | null, collation: string | null) => __TAURI_INVOKE<null>("mysql_db_create", { connId, name, charset, collation }),
	/**
	 *  `mysql_db_drop` (conn_id: String, name: String [, confirmed: bool]) -> ()
	 * 
	 *  强确认：数据库级删除不可恢复，首次调用不传 confirmed 时返回带提示的错误，
	 *  前端弹出二次确认（danger）后带 `confirmed: true` 重新调用。
	 */
	mysqlDbDrop: (connId: string, name: string, confirmed: boolean | null) => __TAURI_INVOKE<null>("mysql_db_drop", { connId, name, confirmed }),
	/**
	 *  `mysql_db_switch` (conn_id: String, name: String) -> String 新 connection_id
	 * 
	 *  切库实现为重建连接池（mysql_async 池归还连接时会 COM_RESET_CONNECTION
	 *  重置当前库，USE 不可靠），前端以新 conn_id 替换后刷新对象树与数据网格。
	 */
	mysqlDbSwitch: (connId: string, name: string) => __TAURI_INVOKE<string>("mysql_db_switch", { connId, name }),
	/**  `mysql_table_show_create` (conn_id: String, table: String) -> MySqlTableDdl */
	mysqlTableShowCreate: (connId: string, table: string) => __TAURI_INVOKE<MySqlTableDdl>("mysql_table_show_create", { connId, table }),
	/**  `mysql_table_optimize` (conn_id: String, table: String) -> () */
	mysqlTableOptimize: (connId: string, table: string) => __TAURI_INVOKE<null>("mysql_table_optimize", { connId, table }),
	/**  `mysql_table_rename` (conn_id: String, old_name: String, new_name: String) -> () */
	mysqlTableRename: (connId: string, oldName: string, newName: string) => __TAURI_INVOKE<null>("mysql_table_rename", { connId, oldName, newName }),
	/**
	 *  `mysql_db_edit` (conn_id: String, name: String, charset: String [, collation: String]) -> ()
	 * 
	 *  编辑数据库默认字符集/排序规则（ALTER DATABASE），右键菜单「编辑数据库...」入口。
	 */
	mysqlDbEdit: (connId: string, name: string, charset: string, collation: string | null) => __TAURI_INVOKE<null>("mysql_db_edit", { connId, name, charset, collation }),
	/**
	 *  `mysql_db_find` (conn_id: String, name: String, keyword: String [, max_per_table: u32]) -> Vec<MySqlDbFindHit>
	 * 
	 *  全库表数据按关键字 LIKE 搜索（右键菜单「在数据库中查找」），
	 *  仅搜字符串列，按表分组返回命中行。
	 */
	mysqlDbFind: (connId: string, name: string, keyword: string, maxPerTable: number | null) => __TAURI_INVOKE<MySqlDbFindHit[]>("mysql_db_find", { connId, name, keyword, maxPerTable }),
	/**  `mysql_user_list` (conn_id: String) -> Vec<MySqlUserInfo> */
	mysqlUserList: (connId: string) => __TAURI_INVOKE<MySqlUserInfo[]>("mysql_user_list", { connId }),
	/**  `mysql_user_create` (conn_id: String, user: String, host: String, password: String) -> () */
	mysqlUserCreate: (connId: string, user: string, host: string, password: string) => __TAURI_INVOKE<null>("mysql_user_create", { connId, user, host, password }),
	/**  `mysql_user_drop` (conn_id: String, user: String, host: String) -> () */
	mysqlUserDrop: (connId: string, user: string, host: string) => __TAURI_INVOKE<null>("mysql_user_drop", { connId, user, host }),
	/**  `mysql_user_grants` (conn_id: String, user: String, host: String) -> Vec<MySqlGrantItem> */
	mysqlUserGrants: (connId: string, user: string, host: string) => __TAURI_INVOKE<MySqlGrantItem[]>("mysql_user_grants", { connId, user, host }),
	/**
	 *  `mysql_backup` (conn_id: String, tables: Option<Vec<String>>, file_path: String,
	 *  include_data: Option<bool>, include_create: Option<bool>) -> u64
	 * 
	 *  - `tables` None = 全库所有表；
	 *  - `include_data` None 默认 true（含 INSERT 数据）；
	 *  - `include_create` 对应服务层的 include_drop 开关（true = 附带
	 *    DROP TABLE IF EXISTS；建表结构始终导出）。
	 *  返回导出的数据行数。
	 */
	mysqlBackup: (connId: string, tables: string[] | null, filePath: string, includeData: boolean | null, includeCreate: boolean | null) => __TAURI_INVOKE<number>("mysql_backup", { connId, tables, filePath, includeData, includeCreate }),
	/**
	 *  `mysql_restore` (conn_id: String, file_path: String [, confirmed: bool]) -> u64
	 * 
	 *  覆盖确认由前端负责（与 mysql_import 的 confirmed 流程一致），后端直接执行。
	 *  返回总受影响行数。
	 */
	mysqlRestore: (connId: string, filePath: string, confirmed: boolean | null) => __TAURI_INVOKE<number>("mysql_restore", { connId, filePath, confirmed }),
	/**  `mysql_backup_profile_list` () -> Vec<MySqlBackupProfile> */
	mysqlBackupProfileList: () => __TAURI_INVOKE<MySqlBackupProfile[]>("mysql_backup_profile_list"),
	/**
	 *  `mysql_backup_profile_save` (id: Option<String>, name: String,
	 *  conn_host: Option<String>, tables: Option<Vec<String>>, include_data: bool,
	 *  include_create: bool) -> ()
	 * 
	 *  id None = 新建（生成 uuid）；conn_host = 关联的 MySQL 连接标识（host 描述，
	 *  可选，前端省略时存空串）；tables None = 全库（空表）。
	 */
	mysqlBackupProfileSave: (id: string | null, name: string, connHost: string | null, tables: string[] | null, includeData: boolean, includeCreate: boolean) => __TAURI_INVOKE<null>("mysql_backup_profile_save", { id, name, connHost, tables, includeData, includeCreate }),
	/**  `mysql_backup_profile_delete` (id: String) -> () */
	mysqlBackupProfileDelete: (id: string) => __TAURI_INVOKE<null>("mysql_backup_profile_delete", { id }),
	/**
	 *  `mysql_backup_run_list` () -> Vec<MySqlBackupRun>
	 * 
	 *  运行历史列表（最近 100 条，倒序）。
	 */
	mysqlBackupRunList: () => __TAURI_INVOKE<MySqlBackupRun[]>("mysql_backup_run_list"),
	/**  是否已设置主密码（前端据此决定首次设置 / 修改模式） */
	masterPasswordStatus: () => __TAURI_INVOKE<boolean>("master_password_status"),
	/**
	 *  设置主密码。
	 * 
	 *  - 首次设置（当前无主密码）：注册保险库 DEK 信封，此后已存凭据转加密存储
	 *  - 修改（当前已有主密码）：须提供 `old_password` —— 先用它迁移 DEK 信封
	 *    （旧密码错误时拒绝更新，防止已存凭据变成不可解），成功后再覆盖哈希
	 */
	masterPasswordSet: (password: string, oldPassword: string | null) => __TAURI_INVOKE<null>("master_password_set", { password, oldPassword }),
	/**  验证主密码；尚未设置时返回 Ok(false) */
	masterPasswordVerify: (password: string) => __TAURI_INVOKE<boolean>("master_password_verify", { password }),
	/**  `vault_status` () -> VaultStatus（has_master_password / unlocked） */
	vaultStatus: () => __TAURI_INVOKE<VaultStatus>("vault_status"),
	/**
	 *  `vault_unlock` (password: String) -> 以主密码解锁保险库（解包 DEK 入内存）
	 * 
	 *  主密码错误时返回带提示错误（AEAD 认证失败），不泄露哈希信息。
	 *  解锁成功后自动迁移明文凭据存量（sessions.auth_type / 已存连接 / 代理密码），
	 *  迁移失败仅记录不阻塞解锁。
	 */
	vaultUnlock: (password: string) => __TAURI_INVOKE<null>("vault_unlock", { password }),
	/**  `vault_lock` () -> 锁定保险库（丢弃内存 DEK），后续凭据读写需重新解锁 */
	vaultLock: () => __TAURI_INVOKE<null>("vault_lock"),
	/**
	 *  `vault_encrypt` (plain: String) -> String（`v1$nonce$cipher`，hex）
	 * 
	 *  供保存路径在后端加密明文凭据后落 settings；未解锁时返回带提示错误。
	 */
	vaultEncrypt: (plain: string) => __TAURI_INVOKE<string>("vault_encrypt", { plain }),
	/**  `vault_decrypt` (cipher: String) -> String（读取路径，密文还原明文） */
	vaultDecrypt: (cipher: string) => __TAURI_INVOKE<string>("vault_decrypt", { cipher }),
	/**  全量读取设置项（key -> value 映射；未写入过的键不在结果中，由前端回退默认值） */
	settingsGetAll: () => __TAURI_INVOKE<{ [key in string]: string }>("settings_get_all"),
	/**  按 key 读取单个设置项；未设置时返回 Ok(None) */
	settingsGet: (key: string) => __TAURI_INVOKE<string | null>("settings_get", { key }),
	/**  写入单个设置项（幂等覆盖；value 统一序列化为字符串） */
	settingsSet: (key: string, value: string) => __TAURI_INVOKE<null>("settings_set", { key, value }),
	/**
	 *  删除全部用户数据（恢复到首次运行状态，不可恢复）：清空全部用户数据表 +
	 *  会话日志。含导航树/保存的连接/查询历史/备份档案/快捷命令/键位映射/
	 *  SFTP 收藏/隧道/认证配置/应用设置/主密码保险库；运行中的内存状态重启后重置。
	 */
	userDataClear: () => __TAURI_INVOKE<null>("user_data_clear"),
	/**
	 *  设置关闭到托盘行为（运行时状态 + 托盘图标按需显隐）；AppHandle 由 Tauri 注入，
	 *  JS 调用形态与 bindings 均不破坏。
	 */
	traySetCloseToTray: (enabled: boolean) => __TAURI_INVOKE<null>("tray_set_close_to_tray", { enabled }),
	/**  读取配色方案文件（JSON 文本） */
	schemeReadFile: (path: string) => __TAURI_INVOKE<string>("scheme_read_file", { path }),
	/**  写入配色方案文件（JSON 文本，已存在时覆盖） */
	schemeWriteFile: (path: string, content: string) => __TAURI_INVOKE<null>("scheme_write_file", { path, content }),
	/**  读取会话级 SSH 选项覆盖项（裸 key -> value 映射；未覆盖的键由前端回退全局值） */
	sshoptSessionList: (sessionId: string) => __TAURI_INVOKE<{ [key in string]: string }>("sshopt_session_list", { sessionId }),
	/**  写入会话级 SSH 选项覆盖项（覆盖全局值；value 统一序列化为字符串） */
	sshoptSessionSet: (sessionId: string, key: string, value: string) => __TAURI_INVOKE<null>("sshopt_session_set", { sessionId, key, value }),
	/**  删除会话级 SSH 选项覆盖项（恢复继承全局值） */
	sshoptSessionDelete: (sessionId: string, key: string) => __TAURI_INVOKE<null>("sshopt_session_delete", { sessionId, key }),
	/**  键位映射列表 */
	keyMappingList: () => __TAURI_INVOKE<KeyMapping[]>("key_mapping_list"),
	/**  保存键位映射（新映射生成 id） */
	keyMappingSave: (mapping: KeyMapping) => __TAURI_INVOKE<KeyMapping>("key_mapping_save", { mapping }),
	/**  删除键位映射（前端已二次确认） */
	keyMappingDelete: (id: string) => __TAURI_INVOKE<null>("key_mapping_delete", { id }),
	/**
	 *  建立本地终端连接并打开 PTY/shell；终端输出流走 Channel。
	 *  conn_id：连接路由键（本地终端无持久会话，每标签唯一，由前端生成）。
	 */
	localShellConnect: (connId: string, onOutput: Channel<number[]>) => __TAURI_INVOKE<null>("local_shell_connect", { connId, onOutput }),
	/**  关闭并清理本地终端会话/PTY（标签关闭时调用，Rust 侧同步清理） */
	localShellDisconnect: (id: string) => __TAURI_INVOKE<null>("local_shell_disconnect", { id }),
	/**  键盘输入写入（按连接键路由） */
	localShellWrite: (id: string, data: number[]) => __TAURI_INVOKE<null>("local_shell_write", { id, data }),
	/**  终端尺寸变更（按连接键路由 resize） */
	localShellResize: (id: string, cols: number, rows: number) => __TAURI_INVOKE<null>("local_shell_resize", { id, cols, rows }),
	/**  本地终端会话存活查询：Rust 侧是否持有该会话连接句柄 */
	localShellAlive: (id: string) => __TAURI_INVOKE<boolean>("local_shell_alive", { id }),
	/**
	 *  建立 Telnet 连接（TCP + 最小 IAC 协商）；终端输出流走 Channel。
	 *  id：连接路由键（Telnet 连接无持久会话，每标签唯一，由前端生成）。
	 */
	telnetConnect: (id: string, host: string, port: number | null, onOutput: Channel<number[]>) => __TAURI_INVOKE<null>("telnet_connect", { id, host, port, onOutput }),
	/**  关闭并清理 Telnet 会话（shutdown 双向关闭 TCP） */
	telnetDisconnect: (id: string) => __TAURI_INVOKE<null>("telnet_disconnect", { id }),
	/**  键盘输入写入（按连接键路由） */
	telnetWrite: (id: string, data: number[]) => __TAURI_INVOKE<null>("telnet_write", { id, data }),
	/**  Telnet 会话存活查询：Rust 侧是否持有该会话连接句柄 */
	telnetAlive: (id: string) => __TAURI_INVOKE<boolean>("telnet_alive", { id }),
	/**  枚举本机串口列表（连接表单下拉选择用） */
	serialList: () => __TAURI_INVOKE<SerialPortInfo[]>("serial_list"),
	/**
	 *  打开串口并启动读写循环；终端输出流走 Channel。
	 *  id：连接路由键（串口连接无持久会话，每标签唯一，由前端生成）。
	 *  port_name：串口名（如 "COM3"）；baud_rate：波特率（默认 115200）。
	 */
	serialConnect: (id: string, portName: string, baudRate: number | null, onOutput: Channel<number[]>) => __TAURI_INVOKE<null>("serial_connect", { id, portName, baudRate, onOutput }),
	/**  关闭并清理串口会话 */
	serialDisconnect: (id: string) => __TAURI_INVOKE<null>("serial_disconnect", { id }),
	/**  键盘输入写入（按连接键路由） */
	serialWrite: (id: string, data: number[]) => __TAURI_INVOKE<null>("serial_write", { id, data }),
	/**  串口会话存活查询：Rust 侧是否持有该会话连接句柄 */
	serialAlive: (id: string) => __TAURI_INVOKE<boolean>("serial_alive", { id }),
};

/* Types */
/**  认证配置文件（契约第 5.1 节） */
export type AuthProfile = {
	/**  uuid v4 */
	id: string,
	/**  显示名 */
	name: string,
	/**  认证方式（复用 5 种认证方式，含凭据） */
	auth_type: AuthType,
};

/**
 *  认证方式（5 种，契约第 1 节）
 * 
 *  TS 侧为可辨识联合（discriminated union），tag 字段为 `type`，
 *  值为 `"password" | "publicKey" | "interactive" | "noAuth" | "jump"`。
 */
export type AuthType = 
/**  密码认证 */
{ type: "password"; password: string } | 
/**  私钥认证：私钥文件路径 + 可选口令 */
{ type: "publicKey"; private_key_path: string; passphrase: string | null } | 
/**  交互式（keyboard-interactive） */
{ type: "interactive"; password: string } | 
/**  不验证 */
{ type: "noAuth" } | 
/**  跳板机：引用另一个已存会话 */
{ type: "jump"; jump_session_id: string };

/**  SFTP 文件条目（契约第 1 节） */
export type FileEntry = {
	name: string,
	is_dir: boolean,
	size: number,
	/**  Unix 秒 */
	modified_at: number,
	/**  八进制权限串（如 "644"，本地 Windows 目录返回空串） */
	permissions: string,
};

/**  键位映射（键盘操作由菜单功能、发送字符串等自定义） */
export type KeyMapping = {
	/**  uuid v4 */
	id: string,
	/**  归一化键位组合（如 "ctrl+shift+x" / "alt+f1"） */
	key_combo: string,
	/**  动作类型（send_string | menu_command） */
	action_type: string,
	/**  动作载荷：发送的字符串 或 菜单命令 action 名 */
	payload: string,
};

/**  备份档案（自动运行任务的持久化配置） */
export type MySqlBackupProfile = {
	/**  档案 id（TEXT uuid，新建由服务层生成） */
	id: string,
	/**  档案名称（展示用） */
	name: string,
	/**  关联的 MySQL 连接标识（host 描述，展示用；实际执行用 conn_id 连接池） */
	conn_host: string,
	/**  参与备份的表名列表（空 = 全库） */
	tables: string[],
	/**  true = 含 INSERT 数据，false = 仅结构 */
	include_data: boolean,
	/**
	 *  true = 附带 DROP TABLE IF EXISTS（对齐备份执行的 DROP 开关；
	 *  建表结构始终导出，该字段控制的是 DROP 语句）
	 */
	include_create: boolean,
	/**  创建时间（ISO 8601 字符串） */
	created_at: string,
};

/**  备份运行历史单条记录 */
export type MySqlBackupRun = {
	/**  运行记录 id（SQLite 自增） */
	id: number,
	/**  关联的备份档案 id（TEXT uuid；None = 未关联档案的立即运行） */
	profile_id: string | null,
	/**  备份产物文件路径 */
	file_path: string,
	/**  导出/写入的数据行数 */
	rows_total: number,
	/**  耗时（毫秒；本轮未接入真实调度，由执行方尽力记录，无记录时为 0） */
	duration_ms: number,
	/**  创建时间（ISO 8601 字符串） */
	created_at: string,
	/**  true = 备份成功，false = 失败 */
	success: boolean,
};

/**
 *  字段级变更
 * 
 *  drop 时仅 `name` 有意义，其余字段由前端省略（serde default 兜底）。
 */
export type MySqlColumnChange = {
	/**  动作：add / modify / drop（取值见 ACTION_* 常量） */
	action: string,
	name: string,
	/**  完整类型定义（如 `varchar(255)` / `int unsigned`） */
	data_type?: string,
	is_nullable?: boolean,
	default_value?: string | null,
	comment?: string,
	/**  附加属性（如 `AUTO_INCREMENT`） */
	extra?: string,
};

/**  列信息（information_schema.COLUMNS 组装） */
export type MySqlColumnInfo = {
	name: string,
	/**  完整类型定义（如 `int unsigned` / `varchar(255)`，来自 COLUMN_TYPE） */
	data_type: string,
	is_nullable: boolean,
	/**  默认值（None = 无默认值；NULL 默认值存字符串 "NULL"） */
	default_value: string | null,
	comment: string,
	/**  附加属性（如 `auto_increment` / `VIRTUAL GENERATED`，来自 EXTRA） */
	extra: string,
	/**  键类型：PRI / UNI / MUL（None = 非键列，来自 COLUMN_KEY，等价 SHOW COLUMNS 的 Key 列） */
	key_type: string | null,
	/**  字符集（二进制 / 数值类型列为 None） */
	character_set: string | null,
	/**  排序规则（二进制 / 数值类型列为 None） */
	collation: string | null,
};

/**  MySQL 连接配置（契约 5.1 节） */
export type MySqlConnection = {
	host: string,
	port: number,
	username: string,
	password: string,
	/**  默认数据库（None = 连接时不指定，需在 SQL 中用全限定表名） */
	schema: string | null,
};

/**
 *  数据同步请求（mysql_data_sync）
 * 
 *  按主键比对两表数据；主键结构不一致或缺失时报错。
 */
export type MySqlDataSyncOptions = {
	/**  源表名（source_conn_id 连接的 source_db 库） */
	source_db: string,
	source_table: string,
	/**  目标连接 ID + 库名 + 表名 */
	target_conn_id: string,
	target_db: string,
	target_table: string,
	/**  插入目标端缺失的行 */
	insert_missing: boolean,
	/**  删除目标端多余的行 */
	delete_extra: boolean,
	/**  更新两端都有但内容不一致的行（REPLACE INTO） */
	update_diff: boolean,
};

/**
 *  数据同步比对结果（mysql_data_sync 返回）
 * 
 *  execute=false 时仅有计数与样例；execute=true 为应用后的计数。
 *  样例为差异行的主键值（按主键列序），三组各限 20 条。
 */
export type MySqlDataSyncOutcome = {
	/**  主键列名（按列序） */
	key_columns: string[],
	/**  仅源端有（目标端缺失） */
	only_source: number,
	/**  仅目标端有（源端没有） */
	only_target: number,
	/**  两端都有但非主键列不一致 */
	changed: number,
	sample_source: string[][],
	sample_target: string[][],
	sample_changed: string[][],
};

/**
 *  数据库清单（mysql_db_list 返回）
 * 
 *  host 与 current_db 一并回传：前端「复制 Host」按钮与数据库切换下拉共用，
 *  避免再起一条命令。host 取自连接池 Opts（ip_or_hostname）。
 */
export type MySqlDatabaseList = {
	host: string,
	/**  当前默认数据库（None = 连接时未指定且未 USE，需先选择库） */
	current_db: string | null,
	/**  该连接可见的全部数据库名（SHOW DATABASES 结果，已排序） */
	databases: string[],
};

/**
 *  全库搜索命中（mysql_db_find 返回，按表分组）
 * 
 *  columns 为该表全部列名（SELECT * 的列顺序），rows 为命中行数据；
 *  仅包含有命中的表，rows 行数受 max_per_table 限制。
 */
export type MySqlDbFindHit = {
	table: string,
	columns: string[],
	rows: ((string | null)[])[],
};

/**  表设计变更（apply_change 入参） */
export type MySqlDesignChange = {
	table: string,
	/**  true = 新建表（生成 CREATE TABLE），false = 修改既有表（生成 ALTER TABLE） */
	is_new: boolean,
	/**  字段级变更列表（is_new 时全部视为新增） */
	columns?: MySqlColumnChange[],
	/**  新增的索引列表 */
	indexes?: MySqlIndexInfo[],
	/**  删除的索引名列表（主键用 "PRIMARY" 标识） */
	dropped_indexes?: string[],
	/**  新增的外键列表 */
	foreign_keys?: MySqlForeignKeyInfo[],
	/**  删除的外键名列表 */
	dropped_foreign_keys?: string[],
	/**  引擎变更（None = 不变） */
	engine?: string | null,
	/**  字符集变更（None = 不变） */
	charset?: string | null,
	/**  表注释变更（None = 不变） */
	comment?: string | null,
};

/**  更新预览（预览 -> 确认 -> 执行管道的第一步产物） */
export type MySqlEditPreview = {
	/**  将要执行的完整 UPDATE 语句（值已转义内联） */
	sql: string,
	/**  COUNT(*) 估算的受影响行数 */
	affected_estimate: number,
	/**  是否危险（复用 services/mysql.rs 的 is_dangerous_sql 判定） */
	danger: boolean,
	danger_reason: string | null,
};

/**  执行计划结果 */
export type MySqlExplainResult = {
	/**  "rows" = 传统表格格式；"tree" = 树形文本（EXPLAIN ANALYZE 输出） */
	format: string,
	/**  列名（format = "rows" 时有效，与 rows 逐行对应） */
	columns: string[],
	/**  行数据（None = SQL NULL，值统一序列化为字符串） */
	rows: ((string | null)[])[],
	/**  树形文本（EXPLAIN ANALYZE / FORMAT=TREE 的单列文本） */
	tree: string | null,
};

/**  导出格式（内部 tag 表示：序列化/反序列化为 { "format": "csv" } 等对象） */
export type MySqlExportFormat = { format: "csv" } | { format: "json" } | { format: "sql" };

/**  导出选项 */
export type MySqlExportOptions = {
	/**  导出的查询 SQL（SELECT） */
	sql: string,
	/**  导出格式 */
	format: MySqlExportFormat,
	/**  目标文件路径（前端保存对话框已让用户确认，后端直接覆盖写入） */
	file_path: string,
	/**  SQL 格式时附带 DROP + CREATE TABLE（表结构） */
	include_create_table: boolean,
};

/**  外键信息 */
export type MySqlForeignKeyInfo = {
	name: string,
	/**  本表外键列（按 ORDINAL_POSITION 顺序） */
	columns: string[],
	/**  引用的目标表 */
	ref_table: string,
	/**  引用的目标列（与 columns 一一对应） */
	ref_columns: string[],
	/**  ON DELETE 规则（RESTRICT / CASCADE / SET NULL / NO ACTION，空串 = 未指定） */
	on_delete: string,
	/**  ON UPDATE 规则（同上） */
	on_update: string,
};

/**
 *  数据生成单列规则
 * 
 *  kind 取值：int / decimal / string / uuid / name / phone / email / datetime / fixed；
 *  min/max 用于 int 与 decimal，length 用于 string，values 用于 fixed（候选池），
 *  null_ratio 为 NULL 概率百分比（0-100，None = 不产生 NULL）。
 */
export type MySqlGenerateColumnRule = {
	name: string,
	kind: string,
	min: number | null,
	max: number | null,
	length: number | null,
	values: string[],
	null_ratio: number | null,
};

/**  数据生成请求（mysql_data_generate） */
export type MySqlGenerateOptions = {
	/**  目标表名（当前连接的当前库） */
	table: string,
	/**  生成行数（1-100000） */
	rows: number,
	/**  生成前清空表（TRUNCATE） */
	truncate: boolean,
	/**  每列生成规则 */
	columns: MySqlGenerateColumnRule[],
};

/**  SHOW GRANTS FOR 的每条授权语句（单个用户可能有多条，含同义行） */
export type MySqlGrantItem = {
	/**  完整的 GRANT 语句原文（如 `GRANT SELECT ON *.* TO 'u'@'%'`） */
	grant_sql: string,
};

/**  导入格式（内部 tag 表示：序列化/反序列化为 { "format": "csv" } 等对象） */
export type MySqlImportFormat = { format: "csv" } | { format: "sql" };

/**  导入选项 */
export type MySqlImportOptions = {
	/**  源文件路径 */
	file_path: string,
	/**  目标表（CSV 格式必填；SQL 格式的语句自带表名，此字段仅作展示） */
	table: string,
	/**  导入格式 */
	format: MySqlImportFormat,
	/**  批量插入每批行数（默认 500，服务层 clamp 1-1000） */
	batch_size?: number,
	/**  true = REPLACE INTO 覆盖已有主键 */
	replace: boolean,
};

/**  索引信息 */
export type MySqlIndexInfo = {
	name: string,
	/**  索引覆盖的列（按 SEQ_IN_INDEX 顺序） */
	columns: string[],
	is_unique: boolean,
	is_primary: boolean,
	/**  索引类型（BTREE / FULLTEXT / HASH 等） */
	index_type: string,
};

/**  导入导出结果（rows_total：导出 = 导出行数 / 导入 = 导入行数） */
export type MySqlIoResult = {
	rows_total: number,
	/**  耗时（毫秒） */
	duration_ms: number,
};

/**  数据库对象 DDL（object_ddl 返回） */
export type MySqlObjectDdl = {
	name: string,
	/**  对象类别（同上，IPC 传输为字符串） */
	kind: string,
	/**  完整 CREATE 语句（SHOW CREATE 结果，含 DEFINER / ALGORITHM 等子句） */
	sql: string,
};

/**  数据库对象列表项（object_list 返回） */
export type MySqlObjectInfo = {
	name: string,
	/**  对象类别（小写 view/function/procedure/trigger/event，IPC 传输为字符串） */
	kind: string,
	/**  注释（仅视图有值，来自 information_schema.VIEWS.TABLE_COMMENT；其余对象留空） */
	comment: string,
};

/**  查询历史条目（SQLite 持久化，history_list / history_search 返回） */
export type MySqlQueryHistoryItem = {
	id: number,
	/**  执行该语句的连接标识（表列名 conn_host） */
	conn_id: string,
	sql: string,
	/**  格式 "YYYY-MM-DD HH:MM:SS"（SQLite datetime('now','localtime') 生成） */
	created_at: string,
	/**  执行耗时毫秒数（None = 未记录） */
	duration_ms: number | null,
	/**  当前版本仅记录成功执行的语句（表结构无 success 列，恒为 true，预留扩展） */
	success: boolean,
};

/**  查询结果（分页 + 列名 + 行数据） */
export type MySqlQueryResult = {
	columns: string[],
	/**  None = SQL NULL（值统一序列化为字符串，前端按 NULL 标识渲染） */
	rows: ((string | null)[])[],
	/**  总行数（COUNT(*) 包装查询得出） */
	total: number,
	page: number,
	page_size: number,
};

/**  单行单列更新（按主键定位行，一次只改一列） */
export type MySqlRowUpdate = {
	table: string,
	pk_column: string,
	/**  主键定位值（None = 主键本身为 NULL，按 `pk IS NULL` 定位） */
	pk_value: string | null,
	column: string,
	/**  新值（与 MySqlQueryResult.rows 的 Option<String> 对齐：None = NULL） */
	value: string | null,
	/**  显式 NULL 标识：true 时值按 NULL 写入（区分空串与 NULL，建立信任） */
	is_null: boolean,
};

/**  批量更新（每条按主键定位，逐条执行） */
export type MySqlRowUpdateBatch = {
	table: string,
	updates: MySqlRowUpdate[],
};

/**  已保存查询条目（命名保存，区别于自动记录的查询历史；saved_query_list 返回） */
export type MySqlSavedQueryItem = {
	id: number,
	/**  用户命名（表内 UNIQUE 约束，同名保存走覆盖语义） */
	name: string,
	/**  绑定的连接标识（None = 不绑定连接，全局可见） */
	conn_id: string | null,
	sql: string,
	/**  格式 "YYYY-MM-DD HH:MM:SS"（SQLite datetime('now','localtime') 生成） */
	created_at: string,
};

/**
 *  结构同步逐表差异项
 * 
 *  kind：create = 目标缺失该表（sql 为源端 SHOW CREATE TABLE 原文，表名已重限定）；
 *  alter = 双方共有但列定义有差异（sql 为逐条 ALTER）；
 *  same = 结构一致（sql 为空）。
 */
export type MySqlStructureSyncItem = {
	table: string,
	kind: string,
	sql: string,
};

/**  结构同步请求（mysql_structure_sync） */
export type MySqlStructureSyncOptions = {
	/**  源库名（source_conn_id 连接） */
	source_db: string,
	/**  目标连接 ID + 库名 */
	target_conn_id: string,
	target_db: string,
};

/**  结构同步计划（mysql_structure_sync 返回） */
export type MySqlStructureSyncPlan = {
	items: MySqlStructureSyncItem[],
};

/**  表结构 DDL（mysql_table_show_create 返回，SHOW CREATE TABLE 结果） */
export type MySqlTableDdl = {
	table: string,
	sql: string,
};

/**  表设计快照（get_design 返回） */
export type MySqlTableDesign = {
	table: string,
	columns: MySqlColumnInfo[],
	indexes: MySqlIndexInfo[],
	foreign_keys: MySqlForeignKeyInfo[],
	engine: string,
	/**  默认字符集（如 utf8mb4） */
	charset: string,
	comment: string,
};

/**  表信息（表列表命令返回） */
export type MySqlTableInfo = {
	name: string,
	/**  预估行数（InnoDB 下为估算值，来自 information_schema.TABLES.TABLE_ROWS） */
	rows: number,
	comment: string,
	engine: string,
};

/**  数据传输请求（mysql_data_transfer） */
export type MySqlTransferOptions = {
	/**  源库名（source_conn_id 连接，全部 SQL 以 `db`.`table` 限定） */
	source_db: string,
	/**  目标连接 ID（前端 mysql_connect 预先建立的独立连接，可与源同连接） */
	target_conn_id: string,
	/**  目标库名 */
	target_db: string,
	/**  要传输的表名列表（源库中的表，顺序即传输顺序） */
	tables: string[],
	/**  传输结构（目标端建表） */
	include_structure: boolean,
	/**  传输数据（批量 INSERT） */
	include_data: boolean,
	/**  目标表已存在时 DROP 重建（false = 跳过该表结构，数据仍按 include_data 传输） */
	recreate: boolean,
};

/**  数据传输逐表结果（mysql_data_transfer 返回） */
export type MySqlTransferTableResult = {
	table: string,
	/**  传输的行数（仅结构时为 0） */
	rows: number,
	/**  是否跳过（目标表已存在且未开启覆盖重建） */
	skipped: boolean,
};

/**  mysql.user 表中的一行用户信息（User, Host 联合为主键） */
export type MySqlUserInfo = {
	user: string,
	host: string,
	/**  备注（可空，空串表示无备注；mysql.user 表无 Comment 列，字段为契约预留） */
	comment: string,
};

/**
 *  导航树批量重排项（拖拽归类/排序的持久化载荷）
 * 
 *  kind 区分文件夹/会话；parent_id 为其新父级（None = 根级）；
 *  order 为该父级下同类节点中的顺序号（从 1 开始递增，由前端重建）。
 *  字段遵循项目 snake_case 约定（与 SessionNode 等一致）。
 */
export type NodeReorderItem = {
	/**  "folder" | "session" */
	kind: string,
	/**  节点 id（文件夹或会话） */
	id: string,
	/**  新父级（文件夹 id；None = 根级） */
	parent_id: string | null,
	/**  同级同类内顺序号（从 1 开始） */
	order: number,
};

/**  快捷命令（契约第 5.1 节） */
export type QuickCommand = {
	/**  uuid v4 */
	id: string,
	/**  显示名 */
	name: string,
	/**  命令正文（可多行，发送到会话时按行回车） */
	command_text: string,
	/**  所属分组（None = 根级） */
	group_id: string | null,
};

/**  快捷命令树文件夹（契约第 5.1 节） */
export type QuickCommandFolder = {
	/**  uuid v4 */
	id: string,
	/**  文件夹名 */
	name: string,
	/**  父文件夹（None = 根级） */
	parent_id: string | null,
};

/**
 *  快捷命令树节点：文件夹或命令（契约第 5.1 节）
 * 
 *  serde tag 字段为 `kind`，值为 `"folder" | "command"`（internally tagged），
 *  与 `SessionNode` 同模式；层级由 `group_id` / `parent_id` 表达。
 */
export type QuickCommandNode = 
/**  文件夹分组 */
{
	kind: "folder",
} & QuickCommandFolder | 
/**  快捷命令 */
{
	kind: "command",
} & QuickCommand;

/**  Redis 连接配置 */
export type RedisConnection = {
	host: string,
	port: number,
	/**  ACL 用户名（可空） */
	username: string | null,
	/**  密码（可空=无密码 Redis） */
	password: string | null,
	/**  默认库 index */
	db: number,
};

/**  任意命令执行结果（前端按 kind 渲染） */
export type RedisExecResult = {
	/**  "nil" | "int" | "string" | "blob" | "array" | "map" | "status" | "error" */
	kind: string,
	/**  任意 JSON（递归的 serde_json::Value 无法被 specta-typescript 内联，映射为 TS any） */
	value: any,
};

/**  串口信息（连接表单展示用） */
export type SerialPortInfo = {
	/**  串口名（如 "COM3"、"/dev/ttyUSB0"） */
	port_name: string,
	/**  串口类型描述（"USB"/"PCI"/"蓝牙"/"未知"） */
	port_type: string,
};

/**  会话配置（存 Rust 侧 SQLite，契约第 1 节） */
export type SessionConfig = {
	/**  uuid v4 */
	id: string,
	/**  显示名 */
	name: string,
	/**  所属文件夹（None = 根级） */
	folder_id: string | null,
	/**  主机地址 */
	host: string,
	/**  端口，默认 22 */
	port: number,
	/**  用户名 */
	username: string,
	/**  认证方式（5 种） */
	auth_type: AuthType,
	/**  编码，默认 "UTF-8" */
	encoding: string,
	/**  Tab 着色（hex） */
	color: string | null,
	/**  保活间隔（秒），默认 30 */
	keepalive_interval: number,
	/**
	 *  引用的认证配置文件 id（可选，None = 使用会话自身认证配置）。
	 *  serde default：老数据缺该字段时反序列化为 None，向后兼容 P0 流程。
	 */
	profile_id?: string | null,
	/**
	 *  会话类型：Some("mysql") = 数据库会话，Some("telnet"/"rlogin") = Telnet 兼容，
	 *  Some("serial") = 串口，None 或 Some("ssh") = SSH 会话。
	 *  serde default：老数据缺该字段时反序列化为 None（视为 SSH），向后兼容。
	 */
	session_type?: string | null,
	/**  串口会话：端口名（session_type == "serial" 时生效） */
	serial_port?: string | null,
	/**  串口会话：波特率（默认 115200，由前端给缺省值） */
	baud_rate?: number | null,
	/**  备注/说明（可选，serde default：老数据缺该字段时反序列化为 None，向后兼容） */
	description?: string | null,
	/**  最后修改时间（Unix 秒；serde default：老数据缺该字段时反序列化为 0，向后兼容） */
	updated_at?: number,
	/**
	 *  手工排序序号（0 = 未手工排序，按名称兜底；同级同类内参与者按此值升序）。
	 *  serde default：老数据缺该字段时反序列化为 0，向后兼容。
	 */
	sort_order?: number,
};

/**  会话树文件夹 */
export type SessionFolder = {
	/**  uuid v4 */
	id: string,
	/**  文件夹名 */
	name: string,
	/**  父文件夹（None = 根级） */
	parent_id: string | null,
	/**  手工排序序号（0 = 未手工排序，按名称兜底） */
	sort_order?: number,
};

/**
 *  会话树节点：文件夹或会话（契约第 1 节）
 * 
 *  serde tag 字段为 `kind`，值为 `"folder" | "session"`；
 *  层级由 `folder_id` / `parent_id` 表达，`session_list` 返回扁平全量列表。
 */
export type SessionNode = {
	kind: "folder",
} & SessionFolder | {
	kind: "session",
} & SessionConfig;

/**  收藏路径条目（side: local | remote，便于下拉按窗格侧过滤，避免跨侧误跳转） */
export type SftpFavorite = {
	/**  uuid v4 */
	id: string,
	/**  路径所属侧：local | remote */
	side: string,
	/**  收藏的目录绝对路径 */
	path: string,
	/**  收藏时间（Unix 秒） */
	created_at: number,
};

/**  一键全启结果报告（start_all 返回，前端展示成功/失败计数） */
export type StartAllReport = {
	/**  规则总数（含已在运行中被跳过的） */
	total: number,
	/**  本次成功启动数 */
	started: number,
	/**  启动失败数 */
	failed: number,
	/**  失败原因列表（与 failed 计数对应） */
	errors: string[],
};

/**  session_test 的返回结构（契约：`{ ok: bool, message: String }`） */
export type TestResult = {
	ok: boolean,
	message: string,
};

/**  传输方向：上传（本地 → 远端）/ 下载（远端 → 本地） */
export type TransferKind = "Upload" | "Download";

/**  传输状态：排队 → 运行 → 完成 / 失败 / 已取消 */
export type TransferStatus = "Queued" | "Running" | "Completed" | "Failed" | "Cancelled";

/**  传输任务（TS 侧同名同构） */
export type TransferTask = {
	id: string,
	session_id: string,
	kind: TransferKind,
	local_path: string,
	remote_path: string,
	total_bytes: number,
	transferred_bytes: number,
	status: TransferStatus,
	error: string | null,
};

/**  隧道类型 */
export type TunnelKind = 
/**  本地转发：本地监听端口 → SSH → target_host:target_port */
"Local" | 
/**  远程转发：SSH 侧监听（P1 简化为记录配置，启动时返回明确错误） */
"Remote" | 
/**  SOCKS5 代理：本地最小 SOCKS5 服务端，目标经 SSH direct-tcpip 转发 */
"Socks";

/**  SSH 隧道规则（契约第 5.1 节） */
export type TunnelRule = {
	/**  uuid v4 */
	id: string,
	/**  所属 SSH 会话 id（= SessionConfig.id） */
	session_id: string,
	/**  隧道类型：Local | Remote | Socks */
	kind: TunnelKind,
	/**  本地监听地址，默认 127.0.0.1 */
	listen_host: string,
	/**  本地监听端口 */
	listen_port: number,
	/**  目标主机：Local/Remote 为转发目标；Socks 为空串 */
	target_host: string,
	/**  目标端口：Local/Remote 为目标端口；Socks 为 0 */
	target_port: number,
	/**  会话连接时是否自动启动 */
	enabled: boolean,
	/**  运行状态：Stopped | Listening | Error */
	status: TunnelStatus,
	/**  错误信息（status = Error 时非空） */
	error: string | null,
};

/**  隧道状态 */
export type TunnelStatus = 
/**  已停止 */
"Stopped" | 
/**  监听中 */
"Listening" | 
/**  错误（error 字段携带原因） */
"Error";

/**  保险库状态（vault_status 返回） */
export type VaultStatus = {
	/**  是否已设置主密码（未设置时凭据沿用明文存储，向后兼容） */
	has_master_password: boolean,
	/**  当前是否已解锁（解锁后 vault_encrypt/vault_decrypt 可用） */
	unlocked: boolean,
};

